// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LoadDWH.Models.Models;

public partial class Vwventa
{
    public int OrderKey { get; set; }

    public string CustomerKey { get; set; }

    public DateTime? OrderDate { get; set; }

    public string ShipName { get; set; }

    public decimal? Total { get; set; }

    public int? Cantidad { get; set; }

    public string CompanyName { get; set; }

    public string EmployeeName { get; set; }

    public int? DataKey { get; set; }
}